### ISSUE TITLE
Feature Request: --print-response option

### ISSUE THREAD

**Issue by kt3k** [recruit-tech/agreed-server#9]
I suggest `--pretty-print` option for displaying pretty printed json object as agreed-server response. That would be helpful when you debug agreed files through server output.

**Comment by yosuke-furukawa** [comment]
sounds good.
But I would like to re-think `--pretty-print` option name more, how about `--print-response` ?

**Comment by kt3k** [comment]
Do you mean `--pretty-response`? If so, I agree with it.

**Comment by yosuke-furukawa** [comment]
I dont want `pretty`  prefix, cause I'd like to separate the features to `output response` and `prettify the output`.

`prettify` has another feature for this case.
If you want prettified log,  `--print-response` and `--pretty-print` are nicer.

**Comment by kt3k** [comment]
`--logging` option solved the root motivation of this issue. So I'm closing this.
